name: .NET Core Publish
on:
  create:
    tags:
      - 'v*'

jobs:
  job:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Nuget package
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Chattle/Chattle.csproj
          PACKAGE_NAME: Chattle
